# Generated by Django 2.1.1 on 2018-09-27 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_insumos',
            name='fecha_cadastro',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cad_stock',
            name='cod_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastroCostos.Cad_insumos'),
        ),
        migrations.AlterField(
            model_name='cad_stock',
            name='fec_movimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
