# Generated by Django 2.1.1 on 2018-10-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cad_costos',
            unique_together={('fecha_trabajo', 'cod_insumo', 'modo_pago_c')},
        ),
    ]
