# Generated by Django 2.1.1 on 2018-10-03 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0002_auto_20180927_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_costos',
            name='fecha_trabajo',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cad_costos',
            name='modo_pago_c',
            field=models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], max_length=1),
        ),
    ]
