# Generated by Django 2.1.1 on 2018-10-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0003_auto_20181003_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_stock',
            name='ind_ing_sal',
            field=models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='cad_stock',
            name='modo_pago_m',
            field=models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], default='E', max_length=1),
        ),
    ]
