# Generated by Django 2.1.1 on 2018-10-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0004_auto_20181006_0106'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cad_un_med',
            name='un_med_insumo_idx',
        ),
    ]
