# Generated by Django 2.1.1 on 2018-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0005_auto_20181006_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad_ing_ret',
            name='notas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
