# Generated by Django 2.1.1 on 2018-10-10 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0006_cad_ing_ret_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_est_finan',
            name='saldo_finan',
        ),
        migrations.RemoveField(
            model_name='cad_est_finan',
            name='tot_costo',
        ),
        migrations.RemoveField(
            model_name='cad_est_finan',
            name='tot_ingresos',
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='costo_acum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='costo_efectivo_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='costo_tarjeta_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='ingreso_acum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='ingreso_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='res_econom_acum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='res_econom_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='res_finan_acum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='res_finan_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='saldo_caja_acum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='saldo_caja_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='saldo_caja_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='stock_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad_est_finan',
            name='stock_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cad_costos',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cad_costos',
            name='valor_costo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cad_ing_ret',
            name='valor_ing_ret',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cad_stock',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cad_stock',
            name='valor_insumo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cad_v_mesas',
            name='fecha_trabajo',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cad_v_mesas',
            name='valor_vendido',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
